services:
  texture_engine:
    build: ./apps/texture_engine/.
    env_file:
    - ./apps/texture_engine/.env
    # volumes:
    # - "./output:/home/huggingface/output/"
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  texura_api:
    build: ./apps/texura_api/.
    env_file:
    - ./apps/texura_api/.env
    ports:
      - "7070:7070"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data: