services:
  texture_engine:
    build: ./apps/texture_engine/.
    env_file:
    - ./apps/texture_engine/.env
    volumes:
    - ./apps/texture_engine/src/:/home/huggingface/
    # - "./output:/home/huggingface/output/"
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  texura_api:
    build: ./apps/texura_api/.
    env_file:
    - ./apps/texura_api/.env
    ports:
      - "7070:7070"
    depends_on:
      - rabbitmq

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  

volumes:
  minio-data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  redis_data: